spring:
  profiles:
    active:
    - 8001
---
server:
  port: 8001

mybatis:
  type-aliases-package: com.zsh.cloud.pojo
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

spring:
  profiles: 8001
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  org.gjt.mm.mysql.Driver
    url:  jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total:  5
      max-wait-millis:  200

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true
---
server:
  port: 8002

mybatis:
  type-aliases-package: com.zsh.cloud.pojo
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

spring:
  profiles: 8002
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  org.gjt.mm.mysql.Driver
    url:  jdbc:mysql://localhost:3306/cloudDB02
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total:  5
      max-wait-millis:  200

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microservicecloud-dept8002
    prefer-ip-address: true
---
server:
  port: 8003

mybatis:
  type-aliases-package: com.zsh.cloud.pojo
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

spring:
  profiles: 8003
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  org.gjt.mm.mysql.Driver
    url:  jdbc:mysql://localhost:3306/cloudDB03
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total:  5
      max-wait-millis:  200

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microservicecloud-dept8003
    prefer-ip-address: true